from app.routes.region_route import regionRouter
from app.routes.category_route import categoryRouter
from app.routes.layer_route import layerRouter
from app.routes.vector_route import vectorRouter
from app.routes.trend_route import trendRouter
from app.routes.custom_shape_route import customshapeRouter
from app.routes.custom_district_route import customdistrictRouter
from app.routes.layer_details_route import layerdetailsRouter
from app.routes.raster_route import rasterRouter
from app.routes.current_layer import currentlayerRouter
from app.routes.usecase import usecaseRouter
from app.routes.download_route import downloadRoute
from app.routes.lulc_route import lulcRoute
from app.routes.warehouse_route import warehouseRouter
from app.routes.cropfire_route import cropfireRouter
from app.routes.pixel_route import pixelRouter
